### ISSUE TITLE
国内企业级低代码开发平台推荐

### ISSUE THREAD

**Issue by aoliann** [aliaszz/awesome-lowcode-component#6]
白码，一个为企业级需求打造的低代码平台，支持私有化部署，通过白码[低代码开发平台](https://www.bnocode.com/)，构建高质量的应用程序，满足企业多样化的需求，自研的AIR低代码(low-code)引擎，提供低代码/无代码两种开发方式，提供丰富的功能模块和可视化组件，企业轻松应对复杂业务需求，快速设计、开发和交付解决方案。
白码低代码官网：[https://www.bnocode.com/](https://www.bnocode.com/)

**Comment by aliaszz** [comment]
感谢关注，已将「白码」平台优先级提高。
